baseURL = "https://yunea.github.io/hugoblog-test/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "anubis2"
title = "Aina Dirou"

[pagination]
pagerSize = 5

[params]
description = "Anubis2 is another simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true

readNextPosts = 2

rssAsSocialIcon = true
locale = "en"
toc = true

[params.author]
name = "Aina"
email  = "aina201.ad@gmail.com"
location = "France"


[params.anubis2]
enableMathGlobally = false # MathJax (default is false)
enableCopyCodeButton = false
enableReadMoreButton = false
hideFooterAttribution = true # hide "Powered by Hugo, theme" in footer
colorTheme = "auto"
enableColorThemeSwitcher = true

social = [
    { id = "github", url = "https://github.com/yunea" },
    { id = "linkedin", url = "https://www.linkedin.com/ainadirou" },
    { id = "email", url = "aina201.ad@gmail.com" },
]

customCSS = [
    "custom-css/custom1.scss", 
    "custom-css/custom2.css",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
]

customJS = [
    "https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"
]


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "EN"

[languages.fr]
languageName = "FR"

[[languages.fr.menu.main]]
identifier = "home"
name = "Accueil"
url = "/"
weight = 1

[[languages.fr.menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 2

[[languages.fr.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[languages.fr.menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 4

[languages.fr.params]
languageCode = "fr"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "d01ce82c-c8f4-4714-ba37-ba4899f2a885"                                            # Website ID
datacache = false
url = "https://umami.xtra.science/script.js"
shareUrl = "https://umami.xtra.science/share/Fy0goUn0b9rrxxGe/hugo-theme-anubis2.netlify.app"

[params.GoogleAnalytics]
enabled = true
gtag = "G-32F16X8HLF"
